export PYTHONPATH=$PYTHONPATH:/home/jayden/Desktop/Programs/aithermostat/
python train_from_dagger40.py
python train_from_dagger45.py
python train_from_dagger50.py
python train_from_dagger55.py
python train_from_dagger60.py
python train_from_dagger65.py
python train_from_dagger70.py
python train_from_dagger75.py
python train_from_dagger80.py